language: go

services:
  - docker

go:
- 1.8
- 1.9

env:
  global:
  - REPO="codem8s/cloud-file-server"
  - VERSION=0.0.1
  - COMMIT=${TRAVIS_COMMIT::6}
  # Quay user
  - secure: "Apsb6sbE6p30vNYmImUiHayzd4fTJxW+BgbTR+A7JjF/qFwrJvagMvFxlqyWYGMyRlQ9wm6/eiEjJu19/ovx4Z6+pWYl5FlPuzHgG+Zxfvybs3TA8Lnu6CKdADSGoP2QioP+u7eXbdsEqmGCBFhVl+8DKcqjntdHXf9VcohlOlQx9H4cSO23IPdTIIg6urhrS6nS5pA5acsKPD9wHwiWDrCJ0PPyrac4sqbMqIYM4PsBtDg3Jkgsh6SE4WkbMDpjw7RYMhKTlPG+V1x7IdVehxqMHqI3Dxs0p7GtRL8U+C+l8D30/LXiT8x/1k0SXJK0q+Kbvrc6ZtNKN8RBGiJCH9ixmo6BswUumqC5LWiTJRV4lQ4v5aAXQIYi4WCODUVp9s+jlGX7vcxokocfuKDPepvaok0iViNRjp4LDrk2i1xrt/P4t7X817+O39SmyPOLqHb2gkTa5Rhf2UU/uyKqeMqJPPr34wrpOqDGmjs/uqCOw0oVZILbpAk/2KUOMo1QM1LHobyohV+1KHb/DewXYbJ8mcdt5y0b2aO1lI2T3HnGvJoXRGTtJDE3SVqZ65a0yUx5MMHm5jl3OHWpg3eC7faPfADhOmrl/3mfZ1V8NBWV5HFPKkJBBGG6HQaqzUOcIaG2ranzxMtTYIVWr20UqvQ46b08Hck69kEUdTccqB4="
  # Quay pass
  - secure: secure: "Ir1+NZw/EuSdm/6uDsVj/ehWx6K7AAkygFv5newaQEHEdS5R2tyv+E34TSXKFxm/b8eb9vQuSbYlJ5MVhm/7eivNbGJdB31AvKfswPtkMrhmvf8ffYmhnJcUgWC2O+0LYO3qgw6qcdRoRGGPg3+vV/aW+5B0vq9ZI4Bk3zkTi/FLJXbRx18Mbvj27h0faDZthhEc5JzaZHhbx6QwcpDryPuBenuLl3tDOjP6ONbLuOdjCd3urHlSXU7iyn7XNQLkYZcTy+88AYtJ+kpLSQs8LUwz7gB9v3/EM8rjGD7Qw5FV/96V/ifWDA5g6NvNLTF4UXoOPv9ytIq0Z3UFmKNUFkkzn8LWtkCW9VHq7V+bzDyYsBw9nls4MQB/K4m6UBtCRl4AZXyhj9gm5/h2oNgytuZooZVOaik4tRJVjIaOi6xdPYm0yhinvrSGa4I08EaDANQaPSYNfG8bX5/C3Zm7hNRnD6jxM0LBcAU/f9IzQV98znPFME1s/XLpg/QslYNZFQMrtkwdttEI0687sVdmvE0zhYSe9sHJFsXacG9Di+K/26GNYmsKG6hdAOiyoYG5WsrEnLAxMyK/xEm0E2W+bUUIYIaf80k0VsSW1kuQSm26+/WkUdg+Pp9eiG7QMesYihm9pPcKWZK77HqdORWF8p3efLwYdoK8+YvQ1vPdd1g="

matrix:
  fast_finish: true

before_install:
- go get -u github.com/golang/dep/cmd/dep

install:
- dep ensure

before_script:
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/golang/lint/golint
- go get -u golang.org/x/tools/cmd/goimports
- go get -u golang.org/x/tools/cmd/godoc

script:
- "./test.sh"
- "./build.sh"
- "./pre-commit.sh"

after_success:
- "./test.sh with-coverage"
- "./release.sh"
